services:
  sgapp:
    image: cronhandler:latest
    build: 
      context: ..
      dockerfile: docker/Dockerfile  # Path to Dockerfile inside docker/ folder
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ../cron:/app/cron   # Mount cron directory if you have more scripts
      - ../data:/app/data    # Mount data directory for testing
    ports:
      - "8000:8000"

  cron:
    image: cronhandler:latest  # Use the same image as the app
    build:
      context: ..
      dockerfile: docker/Dockerfile  # Path to Dockerfile inside docker/ folder
    volumes:
      - ../cron:/app/cron   # Mount cron directory
      - ../data:/app/data    # Mount data directory
    command: ["/bin/bash", "-c", "cron -f"]  # Override the default command to run cron in the foreground
